advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('basic_app/', include('basic_app.urls', namespace='basic_app')),
]

advcbv/basic_app/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name='detail'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.SchoolDeleteView.as_view(), name='delete'),
]

advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse

class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={'pk': self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

advcbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.http import HttpResponse
from . import models

class IndexView(TemplateView):
    template_name = 'index.html'


class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'


class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School


class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School


class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>School</title>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<ul class="nav navbar-nav">
				<li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
				<li><a class="navbar-list" href="{% url 'admin:index' %}">Admin</a></li>
			</ul>
		</nav>
		<div class="container">
			{% block body_block %}
			{% endblock %}
		</div>
	<body>
</html>

advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<h1>Delete {{school.name}}?</h1>
<form method="post">
	{% csrf_token %}
	<input type="submit" class="btn btn-danger" value="Delete">
	<a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
</form>
{% endblock %}

advcbv/basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
<div class="jumbotron">
	<h1>Welcome to the School Detail Page</h1>
	<h2>School details:</h2>
	<p>Name: {{ school_detail.name }}</p>
	<p>Principal: {{ school_detail.principal }}</p>
	<p>Location: {{ school_detail.location }}</p>
	<h3>Students:</h3>
	{% for student in school_detail.students.all %}
	<p>{{student.name}} who is {{student.age}} years old.</p>
	{% endfor %}
</div>

<div class="container">
	<p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>
</div>
{% endblock %}

advcbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<h1>
	{% if not form.instance.pk %}
	Create School
	{% else %}
	Update School
	{% endif %}
</h1>
<form method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" class="btn btn-primary" value="Submit">
</form>
{% endblock %}

advcbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}

<h1>Welcome to a list of all the schools!</h1>
<ol>
	{% for school in schools %}
	<h2><li><a href="{% url 'basic_app:detail' school.pk %}">{{ school.name }}</a></li></h2>
	{% endfor %}
</ol>
<div class="container">
    <p><a class="btn btn-warning" href="{% url 'basic_app:create' %}">Create</a></p>
</div>

{% endblock %}

advcbv/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Base</title>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
	</head>
	<body>
		<nav class="navbar navbar-default navbar-static-top">
			<ul class="nav navbar-nav">
				<li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
				<li><a class="navbar-list" href="{% url 'admin:index' %}">Admin</a></li>
			</ul>
		</nav>
		<div class="container">
			{% block body_block %}
			{% endblock %}
		</div>
	<body>
</html>

advcbv/templates/index.html
{% extends "base.html" %}
{% block body_block %}
<div class="jumbotron">
	<h1>Home Page!</h1>
</div>
{% endblock %}